version: "3.8"

volumes:
  db-data:

services:
  vote:
    image: initcron/vote:latest
    ports:
      - 5000:80
    depends_on:
      - redis

  redis:
    image: redis:alpine

  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  result:
    image: initcron/result:latest
    ports:
      - 5001:4000
    depends_on:
      - db

  worker:
    image: tcrivat/worker:latest
    build: ./worker
    depends_on:
      - redis
      - db
